# Funding options for FWD PRO
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Add your funding links here as the project grows
# github: [Forward-Nexus]
# custom: ["https://fwdai.com/support"]

