# FWD PRO Configuration
# 
# ⚠️ NOTE: This template is REFERENCE ONLY
# The actual config.yaml is generated programmatically by generateConfig() in tools/installer/generators.js
# This file shows the expected structure but is not actively used during installation.
#
# This file is generated during onboarding (npx @fwd-ai/pro install)
# You can edit it anytime to adjust project settings

# Version
version: "1.0.0"

# Project Information
project:
  name: "[PROJECT_NAME]"
  type: "[new/existing]"
  created: "[YYYY-MM-DD]"
  
# Founder Information
founder:
  name: "[FOUNDER_NAME]"
  profile: "~/.fwdpro-global/[name]-profile.md"  # Global profile (reusable)
  communication_style: "[communication_style_from_onboarding]"  # From onboarding - determines expert tone

# Work Focus (array of work types selected in onboarding)
work_types:
  - building     # If selected: Denny + Ada get shortcuts in 0-your-experts/
  - investor     # If selected: Lyna gets shortcut
  - marketing    # If selected: Benji gets shortcut
  - legal        # If selected: Elle gets shortcut
  - operations   # Genna always gets shortcut

# Expert Shortcuts (which experts get links in 0-your-experts/)
# Note: ALL experts are always available in pro-os/experts/ - this just determines shortcuts
your_experts:
  genna: true   # Chief Architect (always gets a shortcut)
  denny: true   # Systems Architect (if "building" in work_types)
  ada: true     # Lead Engineer (if "building" in work_types)
  lyna: false   # External Strategy (if "investor" in work_types)
  benji: false  # Internal Growth (if "marketing" in work_types)
  elle: false   # Legal Counsel (if "legal" in work_types OR HIPAA detected in constraints)

# Command Shortcuts (which commands get links in 0-your-commands/)
# Note: ALL commands are always available in pro-os/commands/ - this just determines shortcuts
# Only flow commands get shortcuts (system commands don't need shortcuts)
your_commands:
  - rt                # Roundtable (always)
  - create-specflow   # Flow commands (if "building" in work_types)
  - execute-specflow

# Tech Stack (if building something)
# Array of strings from onboarding or scanner
tech_stack:
  - "React Native"
  - "Node.js"
  - "PostgreSQL"
  # OR: [] if not applicable/unknown

# AI Tool Configuration
ai_tool: "[cursor/vscode/claude/windsurf/other/generic]"
ide_optimizations: true  # Install IDE-specific optimizations?

# Notes
# - This file is generated from onboarding answers
# - Edit anytime to adjust settings  
# - Experts read this to understand project context
# - Changes take effect immediately (no restart needed)
#
# Actual generation happens in:
# tools/installer/generators.js → generateConfig()
#
# Structure differences from v1.0:
# - work_types is now an array (not object with booleans)
# - your_experts uses object with booleans (correct structure)
# - tech_stack is array of strings (not object with detected/languages/frameworks)
# - Simplified structure (removed unused fields)
#
# For full structure reference, see the actual generated config.yaml in your project

